global.param.p1=1233
global.param.p2=1332

spring.h2.console.enabled=true
spring.cloud.discovery.enabled=true
aureka.client.service-url.defaultZone=http://localhost:8761/eureka
aureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

#http://localhost:8083/swagger-ui/index.html